exclude: '^src/(algorithm|frontend)/'
repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3.7
    args: ['--line-length=120']
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=1024']
  - id: flake8
