language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - docker

before_install:
  - docker image build -t "wohnung-suche:latest" -f src/Dockerfile src/

install:
  - pip install -r requirements

script:
  - pytest
