language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - docker

before_install:
  - docker build -f src/Dockerfile

install:
  - pip install -r requirements

script:
  - pytest
