version: "2"

services:

  redis:
    image: redis:6.0.5
    ports:
      - 6379:6379


  app:
    build: ./src
    ports:
    - 80:5000
    environment:
    - FLASK_ENV=development
    - DEBUG=true
    - SENTRY_DSN=$SENTRY_DSN
    - REDIS_URL=redis://redis:6379
    command: ["python", "app.py"]
    volumes:
    - $PWD/src:/srv
    depends_on:
      - redis

  worker:
    build: ./src
    environment:
      - TRELLO_TOKEN=$TRELLO_TOKEN
      - TRELLO_KEY=$TRELLO_KEY
      - REDIS_URL=$REDIS_URL
    command: ["rq", "worker", "--sentry-dsn", "${SENTRY_DSN}", "--url", "${REDIS_URL}", "cardupdater"]
    depends_on:
      - app
      - redis
    volumes:
      - $PWD/src:/srv
