version: "2"

services:

  app:
    build: src
    ports:
    - 80:5000
    environment:
    - FLASK_ENV=development
    - DEBUG=true
    - SENTRY_DSN=$SENTRY_DSN
    command: ["python", "app.py"]
    volumes:
    - $PWD/src:/srv
