#!/usr/bin/env bash

# go back to the root directory
cd "${0%/*}/.."

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin hub.docker.com
echo "Pushing built image to docker registry"
docker push anubhavcodes/wohnung-suche
