#!/usr/bin/env bash

#go back to the root directory
cd "${0%/*}/.."

# make sure you have `pre-commit` installed

echo "Building images"
docker-compose build

echo "Installing hooks, please install pre-commit before this."
pre-commit install

echo "All set now!! You can start developing."
echo "Run docker-compose up -d to start the app"
